# Generated by Django 3.1.7 on 2021-05-13 09:35

import API_basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/default.jpg', upload_to=API_basic.models.user_directory_path)),
                ('status', models.CharField(choices=[('uploaded', 'UPLOADED'), ('archived', 'ARCHIVED')], default='uploaded', max_length=100)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
