# Generated by Django 3.1.7 on 2021-05-13 17:35

import API_basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=API_basic.models.user_directory_path)),
                ('status', models.CharField(choices=[('uploaded', 'UPLOADED'), ('archived', 'ARCHIVED')], max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('downloadURL', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
